version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    ports:
      - 80:80
  database:
   image: postgres:9.6
   volumes:
     - dbdata:/var/lib/pgsql
   environment:
     - "POSTGRES_DB=default"
     - "POSTGRES_USER=default"
     - "POSTGRES_PASSWORD=secret123!"
  # Testing tools

volumes:
  dbdata: {}